const LMorePro = [
    {
        id: "1",
        imgUrl: "/assests/product-1.png",
        numberOfStars: 4,
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$49.42",
        costAfter: 42.43,
        sold: false,
        numOfSold: "20% off",
        text: "Add To Card",
    },
    {
        id: 2,
        imgUrl: "/assests/product-2.png",
        numberOfStars: 2,
        explore: "Level 20 RGB Cherry",
        costBefore: "$32.99",
        costAfter: 29.99,
        sold: true,
        numOfSold: "20% off",
        text: "Add To Card",
    },
    {
        id: "3",
        imgUrl: "/assests/product-3.png",
        numberOfStars: 3,
        explore: "Logitech Streamcam",
        costBefore: "$29.8",
        costAfter: 12.43,
        sold: false,
        numOfSold: "20% off",
        text: "Add To Card",
    },
    {
        id: "4",
        imgUrl: "/assests/product-4.png",
        cart: true,
        numberOfStars: 3,
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$49.42",
        costAfter: 42.43,
        sold: true,
        numOfSold: "20% off",
        text: "Add To Card",
    },
    {
        id: "6",
        imgUrl: "/assests/product-6.png",
        numberOfStars: 3,
        explore: "Mice Logitech",
        costBefore: "$49.42",
        costAfter: 42.43,
        sold: false,
        numOfSold: "20% off",
        text: "Add To Card",
    },
    {
        id: "7",
        imgUrl: "/assests/product-7.png",
        numberOfStars: 5,
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$49.42",
        costAfter: 42.43,
        sold: true,
        numOfSold: "20% off",
        text: "Add To Card",
    },
    {
        id: "8",
        imgUrl: "/assests/product-2.png",
        numberOfStars: 3,
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$29.42",
        costAfter: 45.73,
        sold: true,
        numOfSold: "10% off",
        text: "Add To Card",
    },
    {
        id: "5",
        imgUrl: "/assests/product-3.png",
        numberOfStars: 1,
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$29.2",
        costAfter: 12.43,
        sold: true,
        numOfSold: "50% off",
        text: "Add To Card",
    },
    {
        id: "9",
        imgUrl: "/assests/product-9.png",
        numberOfStars: 1,
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$29.2",
        costAfter: 12.43,
        sold: true,
        numOfSold: "50% off",
        text: "Add To Card",
    },
    {
        id: "10",
        imgUrl: "/assests/product-10.png",
        numberOfStars: 1,
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$29.2",
        costAfter: 12.43,
        sold: true,
        numOfSold: "50% off",
        text: "Add To Card",
    },
    {
        id: "11",
        imgUrl: "/assests/product-11.png",
        numberOfStars: 1,
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$29.2",
        costAfter: 12.43,
        sold: true,
        numOfSold: "50% off",
        text: "Add To Card",
    },
    {
        id: "12",
        imgUrl: "/assests/product-12.png",
        numberOfStars: 1,
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$29.2",
        costAfter: 12.43,
        sold: true,
        numOfSold: "50% off",
        text: "Add To Card",
    },
];
export default LMorePro;
