const ListWeeks = [
    {
        id: "1",
        imgUrl: "/assests/product-1.png",
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$49.42",
        costAfter: "$42.43",
        sold: true,
        numOfSold: "20% off",
        text: "Add To Card",
    },
    {
        id: "2",
        imgUrl: "/assests/product-2.png",
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$49.42",
        costAfter: "$42.43",
        sold: false,
        numOfSold: "20% off",
        text: "Add To Card",
    },
    {
        id: "3",
        imgUrl: "/assests/product-3.png",
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$49.42",
        costAfter: "$42.43",
        sold: false,
        numOfSold: "20% off",
        text: "Add To Card",
    },
    {
        id: "4",
        imgUrl: "/assests/product-4.png",
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$49.42",
        costAfter: "$42.43",
        sold: false,
        numOfSold: "20% off",
        text: "Add To Card",
    },
    {
        id: "5",
        imgUrl: "/assests/product-5.png",
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$49.42",
        costAfter: "$42.43",
        sold: false,
        numOfSold: "20% off",
        text: "Add To Card",
    },
    {
        id: "6",
        imgUrl: "/assests/product-6.png",
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$49.42",
        costAfter: "$42.43",
        sold: false,
        numOfSold: "20% off",
        text: "Add To Card",
    },
    {
        id: "7",
        imgUrl: "/assests/product-7.png",
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$49.42",
        costAfter: "$42.43",
        sold: false,
        numOfSold: "20% off",
        text: "Add To Card",
    },
    {
        id: "8",
        imgUrl: "/assests/product-8.png",
        explore: "Yantiti Leather & Canvas Bags",
        costBefore: "$49.42",
        costAfter: "$42.43",
        sold: false,
        numOfSold: "20% off",
        text: "Add To Card",
    },
];
export default ListWeeks;
